(function(e, a) { for(var i in a) e[i] = a[i]; }(exports, /******/ (function(modules) { // webpackBootstrap
/******/ 	// The module cache
/******/ 	var installedModules = {};
/******/
/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {
/******/
/******/ 		// Check if module is in cache
/******/ 		if(installedModules[moduleId]) {
/******/ 			return installedModules[moduleId].exports;
/******/ 		}
/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = installedModules[moduleId] = {
/******/ 			i: moduleId,
/******/ 			l: false,
/******/ 			exports: {}
/******/ 		};
/******/
/******/ 		// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
/******/
/******/ 		// Flag the module as loaded
/******/ 		module.l = true;
/******/
/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}
/******/
/******/
/******/ 	// expose the modules object (__webpack_modules__)
/******/ 	__webpack_require__.m = modules;
/******/
/******/ 	// expose the module cache
/******/ 	__webpack_require__.c = installedModules;
/******/
/******/ 	// define getter function for harmony exports
/******/ 	__webpack_require__.d = function(exports, name, getter) {
/******/ 		if(!__webpack_require__.o(exports, name)) {
/******/ 			Object.defineProperty(exports, name, { enumerable: true, get: getter });
/******/ 		}
/******/ 	};
/******/
/******/ 	// define __esModule on exports
/******/ 	__webpack_require__.r = function(exports) {
/******/ 		if(typeof Symbol !== 'undefined' && Symbol.toStringTag) {
/******/ 			Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
/******/ 		}
/******/ 		Object.defineProperty(exports, '__esModule', { value: true });
/******/ 	};
/******/
/******/ 	// create a fake namespace object
/******/ 	// mode & 1: value is a module id, require it
/******/ 	// mode & 2: merge all properties of value into the ns
/******/ 	// mode & 4: return value when already ns object
/******/ 	// mode & 8|1: behave like require
/******/ 	__webpack_require__.t = function(value, mode) {
/******/ 		if(mode & 1) value = __webpack_require__(value);
/******/ 		if(mode & 8) return value;
/******/ 		if((mode & 4) && typeof value === 'object' && value && value.__esModule) return value;
/******/ 		var ns = Object.create(null);
/******/ 		__webpack_require__.r(ns);
/******/ 		Object.defineProperty(ns, 'default', { enumerable: true, value: value });
/******/ 		if(mode & 2 && typeof value != 'string') for(var key in value) __webpack_require__.d(ns, key, function(key) { return value[key]; }.bind(null, key));
/******/ 		return ns;
/******/ 	};
/******/
/******/ 	// getDefaultExport function for compatibility with non-harmony modules
/******/ 	__webpack_require__.n = function(module) {
/******/ 		var getter = module && module.__esModule ?
/******/ 			function getDefault() { return module['default']; } :
/******/ 			function getModuleExports() { return module; };
/******/ 		__webpack_require__.d(getter, 'a', getter);
/******/ 		return getter;
/******/ 	};
/******/
/******/ 	// Object.prototype.hasOwnProperty.call
/******/ 	__webpack_require__.o = function(object, property) { return Object.prototype.hasOwnProperty.call(object, property); };
/******/
/******/ 	// __webpack_public_path__
/******/ 	__webpack_require__.p = "";
/******/
/******/
/******/ 	// Load entry module and return exports
/******/ 	return __webpack_require__(__webpack_require__.s = 0);
/******/ })
/************************************************************************/
/******/ ({

/***/ "./node_modules/@angular/router/router.ngfactory.js":
/*!**********************************************************!*\
  !*** ./node_modules/@angular/router/router.ngfactory.js ***!
  \**********************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
const i0 = __webpack_require__(/*! @angular/core */ "@angular/core");
const i1 = __webpack_require__(/*! @angular/router */ "@angular/router");
var RouterModuleNgFactory = i0.ɵcmf(i1.RouterModule, [], function (_l) { return i0.ɵmod([i0.ɵmpd(512, i0.ComponentFactoryResolver, i0.ɵCodegenComponentFactoryResolver, [[8, [ɵangular_packages_router_router_lNgFactory]], [3, i0.ComponentFactoryResolver], i0.NgModuleRef]), i0.ɵmpd(1073742336, i1.RouterModule, i1.RouterModule, [[2, i1.ɵangular_packages_router_router_a], [2, i1.Router]])]); });
exports.RouterModuleNgFactory = RouterModuleNgFactory;
var styles_ɵangular_packages_router_router_l = [];
var RenderType_ɵangular_packages_router_router_l = i0.ɵcrt({ encapsulation: 2, styles: styles_ɵangular_packages_router_router_l, data: {} });
exports.RenderType_ɵangular_packages_router_router_l = RenderType_ɵangular_packages_router_router_l;
function View_ɵangular_packages_router_router_l_0(_l) { return i0.ɵvid(0, [(_l()(), i0.ɵeld(0, 16777216, null, null, 1, "router-outlet", [], null, null, null, null, null)), i0.ɵdid(1, 212992, null, 0, i1.RouterOutlet, [i1.ChildrenOutletContexts, i0.ViewContainerRef, i0.ComponentFactoryResolver, [8, null], i0.ChangeDetectorRef], null, null)], function (_ck, _v) { _ck(_v, 1, 0); }, null); }
exports.View_ɵangular_packages_router_router_l_0 = View_ɵangular_packages_router_router_l_0;
function View_ɵangular_packages_router_router_l_Host_0(_l) { return i0.ɵvid(0, [(_l()(), i0.ɵeld(0, 0, null, null, 1, "ng-component", [], null, null, null, View_ɵangular_packages_router_router_l_0, RenderType_ɵangular_packages_router_router_l)), i0.ɵdid(1, 49152, null, 0, i1.ɵangular_packages_router_router_l, [], null, null)], null, null); }
exports.View_ɵangular_packages_router_router_l_Host_0 = View_ɵangular_packages_router_router_l_Host_0;
var ɵangular_packages_router_router_lNgFactory = i0.ɵccf("ng-component", i1.ɵangular_packages_router_router_l, View_ɵangular_packages_router_router_l_Host_0, {}, {}, []);
exports.ɵangular_packages_router_router_lNgFactory = ɵangular_packages_router_router_lNgFactory;


/***/ }),

/***/ "./src/app/app-routing.module.ts":
/*!***************************************!*\
  !*** ./src/app/app-routing.module.ts ***!
  \***************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
const router_1 = __webpack_require__(/*! @angular/router */ "@angular/router");
const home_component_1 = __webpack_require__(/*! ./home/home.component */ "./src/app/home/home.component.ts");
const routes = [
    { path: '', component: home_component_1.HomeComponent },
];
class AppRoutingModule {
}
exports.AppRoutingModule = AppRoutingModule;


/***/ }),

/***/ "./src/app/app.component.ngfactory.js":
/*!********************************************!*\
  !*** ./src/app/app.component.ngfactory.js ***!
  \********************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
const i0 = __webpack_require__(/*! ./app.component.scss.shim.ngstyle */ "./src/app/app.component.scss.shim.ngstyle.js");
const i1 = __webpack_require__(/*! @angular/core */ "@angular/core");
const i2 = __webpack_require__(/*! ./navbar/navbar.component.ngfactory */ "./src/app/navbar/navbar.component.ngfactory.js");
const i3 = __webpack_require__(/*! ./navbar/navbar.component */ "./src/app/navbar/navbar.component.ts");
const i4 = __webpack_require__(/*! @angular/router */ "@angular/router");
const i5 = __webpack_require__(/*! ./app.component */ "./src/app/app.component.ts");
var styles_AppComponent = [i0.styles];
var RenderType_AppComponent = i1.ɵcrt({ encapsulation: 0, styles: styles_AppComponent, data: {} });
exports.RenderType_AppComponent = RenderType_AppComponent;
function View_AppComponent_0(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 5, "div", [["class", "all_content"]], null, null, null, null, null)), (_l()(), i1.ɵeld(1, 0, null, null, 1, "app-navbar", [], null, null, null, i2.View_NavbarComponent_0, i2.RenderType_NavbarComponent)), i1.ɵdid(2, 114688, null, 0, i3.NavbarComponent, [], null, null), (_l()(), i1.ɵeld(3, 0, null, null, 2, "div", [["class", "my_routing"]], null, null, null, null, null)), (_l()(), i1.ɵeld(4, 16777216, null, null, 1, "router-outlet", [], null, null, null, null, null)), i1.ɵdid(5, 212992, null, 0, i4.RouterOutlet, [i4.ChildrenOutletContexts, i1.ViewContainerRef, i1.ComponentFactoryResolver, [8, null], i1.ChangeDetectorRef], null, null)], function (_ck, _v) { _ck(_v, 2, 0); _ck(_v, 5, 0); }, null); }
exports.View_AppComponent_0 = View_AppComponent_0;
function View_AppComponent_Host_0(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 1, "app-root", [], null, null, null, View_AppComponent_0, RenderType_AppComponent)), i1.ɵdid(1, 49152, null, 0, i5.AppComponent, [], null, null)], null, null); }
exports.View_AppComponent_Host_0 = View_AppComponent_Host_0;
var AppComponentNgFactory = i1.ɵccf("app-root", i5.AppComponent, View_AppComponent_Host_0, {}, {}, []);
exports.AppComponentNgFactory = AppComponentNgFactory;


/***/ }),

/***/ "./src/app/app.component.scss.shim.ngstyle.js":
/*!****************************************************!*\
  !*** ./src/app/app.component.scss.shim.ngstyle.js ***!
  \****************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = ["\n/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IiIsImZpbGUiOiJzcmMvYXBwL2FwcC5jb21wb25lbnQuc2NzcyJ9 */"];
exports.styles = styles;


/***/ }),

/***/ "./src/app/app.component.ts":
/*!**********************************!*\
  !*** ./src/app/app.component.ts ***!
  \**********************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
class AppComponent {
    constructor() {
        this.title = 'manageLandingPage';
    }
}
exports.AppComponent = AppComponent;


/***/ }),

/***/ "./src/app/app.module.ts":
/*!*******************************!*\
  !*** ./src/app/app.module.ts ***!
  \*******************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
class AppModule {
}
exports.AppModule = AppModule;


/***/ }),

/***/ "./src/app/app.server.module.ngfactory.js":
/*!************************************************!*\
  !*** ./src/app/app.server.module.ngfactory.js ***!
  \************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
const i0 = __webpack_require__(/*! @angular/core */ "@angular/core");
const i1 = __webpack_require__(/*! ./app.server.module */ "./src/app/app.server.module.ts");
const i2 = __webpack_require__(/*! ./app.component */ "./src/app/app.component.ts");
const i3 = __webpack_require__(/*! ../../node_modules/@angular/router/router.ngfactory */ "./node_modules/@angular/router/router.ngfactory.js");
const i4 = __webpack_require__(/*! ./home/home.component.ngfactory */ "./src/app/home/home.component.ngfactory.js");
const i5 = __webpack_require__(/*! ./app.component.ngfactory */ "./src/app/app.component.ngfactory.js");
const i6 = __webpack_require__(/*! @angular/common */ "@angular/common");
const i7 = __webpack_require__(/*! @angular/platform-browser */ "@angular/platform-browser");
const i8 = __webpack_require__(/*! @angular/platform-server */ "@angular/platform-server");
const i9 = __webpack_require__(/*! @angular/animations/browser */ "@angular/animations/browser");
const i10 = __webpack_require__(/*! @angular/platform-browser/animations */ "@angular/platform-browser/animations");
const i11 = __webpack_require__(/*! @angular/router */ "@angular/router");
const i12 = __webpack_require__(/*! @angular/common/http */ "@angular/common/http");
const i13 = __webpack_require__(/*! @angular/animations */ "@angular/animations");
const i14 = __webpack_require__(/*! ./home/home.component */ "./src/app/home/home.component.ts");
const i15 = __webpack_require__(/*! ./app-routing.module */ "./src/app/app-routing.module.ts");
const i16 = __webpack_require__(/*! ./app.module */ "./src/app/app.module.ts");
var AppServerModuleNgFactory = i0.ɵcmf(i1.AppServerModule, [i2.AppComponent], function (_l) { return i0.ɵmod([i0.ɵmpd(512, i0.ComponentFactoryResolver, i0.ɵCodegenComponentFactoryResolver, [[8, [i3.ɵangular_packages_router_router_lNgFactory, i4.HomeComponentNgFactory, i5.AppComponentNgFactory]], [3, i0.ComponentFactoryResolver], i0.NgModuleRef]), i0.ɵmpd(5120, i0.LOCALE_ID, i0.ɵangular_packages_core_core_p, [[3, i0.LOCALE_ID]]), i0.ɵmpd(4608, i6.NgLocalization, i6.NgLocaleLocalization, [i0.LOCALE_ID, [2, i6.ɵangular_packages_common_common_a]]), i0.ɵmpd(5120, i0.ɵangular_packages_core_core_ba, i0.ɵangular_packages_core_core_r, [i0.NgZone]), i0.ɵmpd(5120, i0.IterableDiffers, i0.ɵangular_packages_core_core_n, []), i0.ɵmpd(5120, i0.KeyValueDiffers, i0.ɵangular_packages_core_core_o, []), i0.ɵmpd(4608, i7.DomSanitizer, i7.ɵDomSanitizerImpl, [i6.DOCUMENT]), i0.ɵmpd(6144, i0.Sanitizer, null, [i7.DomSanitizer]), i0.ɵmpd(4608, i7.HAMMER_GESTURE_CONFIG, i7.HammerGestureConfig, []), i0.ɵmpd(5120, i7.EVENT_MANAGER_PLUGINS, function (p0_0, p0_1, p0_2, p1_0, p2_0, p2_1, p2_2, p2_3, p3_0) { return [new i7.ɵDomEventsPlugin(p0_0, p0_1, p0_2), new i7.ɵKeyEventsPlugin(p1_0), new i7.ɵHammerGesturesPlugin(p2_0, p2_1, p2_2, p2_3), new i8.ɵangular_packages_platform_server_platform_server_d(p3_0)]; }, [i6.DOCUMENT, i0.NgZone, i0.PLATFORM_ID, i6.DOCUMENT, i6.DOCUMENT, i7.HAMMER_GESTURE_CONFIG, i0.ɵConsole, [2, i7.HAMMER_LOADER], i6.DOCUMENT]), i0.ɵmpd(4608, i7.EventManager, i7.EventManager, [i7.EVENT_MANAGER_PLUGINS, i0.NgZone]), i0.ɵmpd(135680, i7.ɵDomSharedStylesHost, i7.ɵDomSharedStylesHost, [i6.DOCUMENT]), i0.ɵmpd(4608, i7.ɵDomRendererFactory2, i7.ɵDomRendererFactory2, [i7.EventManager, i7.ɵDomSharedStylesHost, i0.APP_ID]), i0.ɵmpd(4608, i8.ɵangular_packages_platform_server_platform_server_c, i8.ɵangular_packages_platform_server_platform_server_c, [i6.DOCUMENT, [2, i7.ɵTRANSITION_ID]]), i0.ɵmpd(6144, i7.ɵSharedStylesHost, null, [i8.ɵangular_packages_platform_server_platform_server_c]), i0.ɵmpd(4608, i8.ɵServerRendererFactory2, i8.ɵServerRendererFactory2, [i7.EventManager, i0.NgZone, i6.DOCUMENT, i7.ɵSharedStylesHost]), i0.ɵmpd(4608, i9.AnimationDriver, i9.ɵNoopAnimationDriver, []), i0.ɵmpd(5120, i9.ɵAnimationStyleNormalizer, i10.ɵangular_packages_platform_browser_animations_animations_b, []), i0.ɵmpd(4608, i9.ɵAnimationEngine, i10.ɵInjectableAnimationEngine, [i6.DOCUMENT, i9.AnimationDriver, i9.ɵAnimationStyleNormalizer]), i0.ɵmpd(5120, i0.RendererFactory2, i8.ɵangular_packages_platform_server_platform_server_a, [i8.ɵServerRendererFactory2, i9.ɵAnimationEngine, i0.NgZone]), i0.ɵmpd(4352, i0.Testability, null, []), i0.ɵmpd(5120, i11.ActivatedRoute, i11.ɵangular_packages_router_router_g, [i11.Router]), i0.ɵmpd(4608, i11.NoPreloading, i11.NoPreloading, []), i0.ɵmpd(6144, i11.PreloadingStrategy, null, [i11.NoPreloading]), i0.ɵmpd(135680, i11.RouterPreloader, i11.RouterPreloader, [i11.Router, i0.NgModuleFactoryLoader, i0.Compiler, i0.Injector, i11.PreloadingStrategy]), i0.ɵmpd(4608, i11.PreloadAllModules, i11.PreloadAllModules, []), i0.ɵmpd(4608, i6.ViewportScroller, i6.ɵNullViewportScroller, []), i0.ɵmpd(5120, i11.ɵangular_packages_router_router_o, i11.ɵangular_packages_router_router_c, [i11.Router, i6.ViewportScroller, i11.ROUTER_CONFIGURATION]), i0.ɵmpd(5120, i11.ROUTER_INITIALIZER, i11.ɵangular_packages_router_router_j, [i11.ɵangular_packages_router_router_h]), i0.ɵmpd(5120, i0.APP_BOOTSTRAP_LISTENER, function (p0_0) { return [p0_0]; }, [i11.ROUTER_INITIALIZER]), i0.ɵmpd(4608, i12.HttpXsrfTokenExtractor, i12.ɵangular_packages_common_http_http_g, [i6.DOCUMENT, i0.PLATFORM_ID, i12.ɵangular_packages_common_http_http_e]), i0.ɵmpd(4608, i12.ɵangular_packages_common_http_http_h, i12.ɵangular_packages_common_http_http_h, [i12.HttpXsrfTokenExtractor, i12.ɵangular_packages_common_http_http_f]), i0.ɵmpd(5120, i12.HTTP_INTERCEPTORS, function (p0_0) { return [p0_0]; }, [i12.ɵangular_packages_common_http_http_h]), i0.ɵmpd(4608, i12.XhrFactory, i8.ɵangular_packages_platform_server_platform_server_e, []), i0.ɵmpd(4608, i12.HttpXhrBackend, i12.HttpXhrBackend, [i12.XhrFactory]), i0.ɵmpd(6144, i12.HttpBackend, null, [i12.HttpXhrBackend]), i0.ɵmpd(5120, i12.HttpHandler, i8.ɵangular_packages_platform_server_platform_server_f, [i12.HttpBackend, i0.Injector]), i0.ɵmpd(4608, i12.HttpClient, i12.HttpClient, [i12.HttpHandler]), i0.ɵmpd(4608, i12.ɵangular_packages_common_http_http_d, i12.ɵangular_packages_common_http_http_d, []), i0.ɵmpd(4608, i13.AnimationBuilder, i10.ɵBrowserAnimationBuilder, [i0.RendererFactory2, i6.DOCUMENT]), i0.ɵmpd(1073742336, i6.CommonModule, i6.CommonModule, []), i0.ɵmpd(1024, i0.ErrorHandler, i7.ɵangular_packages_platform_browser_platform_browser_a, []), i0.ɵmpd(1024, i0.NgProbeToken, function () { return [i11.ɵangular_packages_router_router_b()]; }, []), i0.ɵmpd(512, i11.ɵangular_packages_router_router_h, i11.ɵangular_packages_router_router_h, [i0.Injector]), i0.ɵmpd(256, i0.APP_ID, "serverApp", []), i0.ɵmpd(2048, i7.ɵTRANSITION_ID, null, [i0.APP_ID]), i0.ɵmpd(1024, i0.APP_INITIALIZER, function (p0_0, p1_0, p2_0, p2_1, p2_2) { return [i7.ɵangular_packages_platform_browser_platform_browser_j(p0_0), i11.ɵangular_packages_router_router_i(p1_0), i7.ɵangular_packages_platform_browser_platform_browser_h(p2_0, p2_1, p2_2)]; }, [[2, i0.NgProbeToken], i11.ɵangular_packages_router_router_h, i7.ɵTRANSITION_ID, i6.DOCUMENT, i0.Injector]), i0.ɵmpd(512, i0.ApplicationInitStatus, i0.ApplicationInitStatus, [[2, i0.APP_INITIALIZER]]), i0.ɵmpd(131584, i0.ApplicationRef, i0.ApplicationRef, [i0.NgZone, i0.ɵConsole, i0.Injector, i0.ErrorHandler, i0.ComponentFactoryResolver, i0.ApplicationInitStatus]), i0.ɵmpd(1073742336, i0.ApplicationModule, i0.ApplicationModule, [i0.ApplicationRef]), i0.ɵmpd(1073742336, i7.BrowserModule, i7.BrowserModule, [[3, i7.BrowserModule]]), i0.ɵmpd(1024, i11.ɵangular_packages_router_router_a, i11.ɵangular_packages_router_router_e, [[3, i11.Router]]), i0.ɵmpd(512, i11.UrlSerializer, i11.DefaultUrlSerializer, []), i0.ɵmpd(512, i11.ChildrenOutletContexts, i11.ChildrenOutletContexts, []), i0.ɵmpd(256, i11.ROUTER_CONFIGURATION, {}, []), i0.ɵmpd(1024, i6.LocationStrategy, i11.ɵangular_packages_router_router_d, [i6.PlatformLocation, [2, i6.APP_BASE_HREF], i11.ROUTER_CONFIGURATION]), i0.ɵmpd(512, i6.Location, i6.Location, [i6.LocationStrategy, i6.PlatformLocation]), i0.ɵmpd(512, i0.Compiler, i0.Compiler, []), i0.ɵmpd(512, i0.NgModuleFactoryLoader, i0.SystemJsNgModuleLoader, [i0.Compiler, [2, i0.SystemJsNgModuleLoaderConfig]]), i0.ɵmpd(1024, i11.ROUTES, function () { return [[{ path: "", component: i14.HomeComponent }]]; }, []), i0.ɵmpd(1024, i11.Router, i11.ɵangular_packages_router_router_f, [i0.ApplicationRef, i11.UrlSerializer, i11.ChildrenOutletContexts, i6.Location, i0.Injector, i0.NgModuleFactoryLoader, i0.Compiler, i11.ROUTES, i11.ROUTER_CONFIGURATION, [2, i11.UrlHandlingStrategy], [2, i11.RouteReuseStrategy]]), i0.ɵmpd(1073742336, i11.RouterModule, i11.RouterModule, [[2, i11.ɵangular_packages_router_router_a], [2, i11.Router]]), i0.ɵmpd(1073742336, i15.AppRoutingModule, i15.AppRoutingModule, []), i0.ɵmpd(1073742336, i16.AppModule, i16.AppModule, []), i0.ɵmpd(1073742336, i12.HttpClientXsrfModule, i12.HttpClientXsrfModule, []), i0.ɵmpd(1073742336, i12.HttpClientModule, i12.HttpClientModule, []), i0.ɵmpd(1073742336, i10.NoopAnimationsModule, i10.NoopAnimationsModule, []), i0.ɵmpd(1073742336, i8.ServerModule, i8.ServerModule, []), i0.ɵmpd(1073742336, i1.AppServerModule, i1.AppServerModule, []), i0.ɵmpd(256, i0.ɵAPP_ROOT, true, []), i0.ɵmpd(256, i12.ɵangular_packages_common_http_http_e, "XSRF-TOKEN", []), i0.ɵmpd(256, i12.ɵangular_packages_common_http_http_f, "X-XSRF-TOKEN", []), i0.ɵmpd(256, i10.ANIMATION_MODULE_TYPE, "NoopAnimations", [])]); });
exports.AppServerModuleNgFactory = AppServerModuleNgFactory;


/***/ }),

/***/ "./src/app/app.server.module.ts":
/*!**************************************!*\
  !*** ./src/app/app.server.module.ts ***!
  \**************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
class AppServerModule {
}
exports.AppServerModule = AppServerModule;


/***/ }),

/***/ "./src/app/home/home.component.ngfactory.js":
/*!**************************************************!*\
  !*** ./src/app/home/home.component.ngfactory.js ***!
  \**************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
const i0 = __webpack_require__(/*! ./home.component.scss.shim.ngstyle */ "./src/app/home/home.component.scss.shim.ngstyle.js");
const i1 = __webpack_require__(/*! @angular/core */ "@angular/core");
const i2 = __webpack_require__(/*! ./home.component */ "./src/app/home/home.component.ts");
var styles_HomeComponent = [i0.styles];
var RenderType_HomeComponent = i1.ɵcrt({ encapsulation: 0, styles: styles_HomeComponent, data: {} });
exports.RenderType_HomeComponent = RenderType_HomeComponent;
function View_HomeComponent_0(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 171, "div", [["class", "home-page"]], null, null, null, null, null)), (_l()(), i1.ɵeld(1, 0, null, null, 0, "div", [["class", "overlay"]], null, null, null, null, null)), (_l()(), i1.ɵeld(2, 0, null, null, 14, "div", [["class", "header"]], null, null, null, null, null)), (_l()(), i1.ɵeld(3, 0, null, null, 0, "img", [["alt", "header-back"], ["src", "../../assets/images/bg-tablet-pattern.svg"]], null, null, null, null, null)), (_l()(), i1.ɵeld(4, 0, null, null, 12, "div", [["class", "container"]], null, null, null, null, null)), (_l()(), i1.ɵeld(5, 0, null, null, 11, "div", [["class", "row"]], null, null, null, null, null)), (_l()(), i1.ɵeld(6, 0, null, null, 7, "div", [["class", "col-md-6"]], null, null, null, null, null)), (_l()(), i1.ɵeld(7, 0, null, null, 6, "div", [["class", "left-info"]], null, null, null, null, null)), (_l()(), i1.ɵeld(8, 0, null, null, 1, "h1", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["bring everyone together to build better products"])), (_l()(), i1.ɵeld(10, 0, null, null, 1, "p", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, [" manage makes it sample for software teams to plan day-to-day takes while keeping the larger team goals in view "])), (_l()(), i1.ɵeld(12, 0, null, null, 1, "button", [["class", "btn btn-primary"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["get start"])), (_l()(), i1.ɵeld(14, 0, null, null, 2, "div", [["class", "col-md-6"]], null, null, null, null, null)), (_l()(), i1.ɵeld(15, 0, null, null, 1, "div", [["class", "right-info"]], null, null, null, null, null)), (_l()(), i1.ɵeld(16, 0, null, null, 0, "img", [["alt", "header-img"], ["src", "../../assets/images/illustration-intro.svg"]], null, null, null, null, null)), (_l()(), i1.ɵeld(17, 0, null, null, 44, "div", [["class", "features"], ["id", "features"]], null, null, null, null, null)), (_l()(), i1.ɵeld(18, 0, null, null, 0, "img", [["alt", "header-back"], ["src", "../../assets/images/bg-tablet-pattern.svg"]], null, null, null, null, null)), (_l()(), i1.ɵeld(19, 0, null, null, 42, "div", [["class", "container"]], null, null, null, null, null)), (_l()(), i1.ɵeld(20, 0, null, null, 41, "div", [["class", "row"]], null, null, null, null, null)), (_l()(), i1.ɵeld(21, 0, null, null, 5, "div", [["class", "col-md-6 col-sm-12"]], null, null, null, null, null)), (_l()(), i1.ɵeld(22, 0, null, null, 4, "div", [["class", "fleft-info"]], null, null, null, null, null)), (_l()(), i1.ɵeld(23, 0, null, null, 1, "h2", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, [" what's different about manage? "])), (_l()(), i1.ɵeld(25, 0, null, null, 1, "p", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, [" manage provides all the functionality your team needs. without the comlexity, our softare is tailer-made for modern digital product teams "])), (_l()(), i1.ɵeld(27, 0, null, null, 34, "div", [["class", "col-md-6 col-sm-12"]], null, null, null, null, null)), (_l()(), i1.ɵeld(28, 0, null, null, 33, "div", [["class", "fright-info"]], null, null, null, null, null)), (_l()(), i1.ɵeld(29, 0, null, null, 10, "div", [["class", "fright-one"]], null, null, null, null, null)), (_l()(), i1.ɵeld(30, 0, null, null, 9, "div", [["class", "row"]], null, null, null, null, null)), (_l()(), i1.ɵeld(31, 0, null, null, 2, "div", [["class", "col-md-2 col-sm-2"]], null, null, null, null, null)), (_l()(), i1.ɵeld(32, 0, null, null, 1, "span", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["01"])), (_l()(), i1.ɵeld(34, 0, null, null, 5, "div", [["class", "col-md-10 col-sm-12"]], null, null, null, null, null)), (_l()(), i1.ɵeld(35, 0, null, null, 4, "div", [["class", "fr-text"]], null, null, null, null, null)), (_l()(), i1.ɵeld(36, 0, null, null, 1, "h4", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["track company-wide progress"])), (_l()(), i1.ɵeld(38, 0, null, null, 1, "p", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, [" see how your day-to-day tasks fit into the wider vision go from tracking progress at the milestone level all the way done to the smallest of details. never lose sight of the bigger picture again "])), (_l()(), i1.ɵeld(40, 0, null, null, 10, "div", [["class", "fright-two"]], null, null, null, null, null)), (_l()(), i1.ɵeld(41, 0, null, null, 9, "div", [["class", "row"]], null, null, null, null, null)), (_l()(), i1.ɵeld(42, 0, null, null, 2, "div", [["class", "col-md-2 col-sm-6"]], null, null, null, null, null)), (_l()(), i1.ɵeld(43, 0, null, null, 1, "span", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["02"])), (_l()(), i1.ɵeld(45, 0, null, null, 5, "div", [["class", "col-md-10 col-sm-6"]], null, null, null, null, null)), (_l()(), i1.ɵeld(46, 0, null, null, 4, "div", [["class", "fr-text"]], null, null, null, null, null)), (_l()(), i1.ɵeld(47, 0, null, null, 1, "h4", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["advanced build-in reports"])), (_l()(), i1.ɵeld(49, 0, null, null, 1, "p", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, [" set internal delivery estimates and track progress toward company goals. our customizable dashboard helps you build out the reports you need to keep key stackholders informed "])), (_l()(), i1.ɵeld(51, 0, null, null, 10, "div", [["class", "fright-three"]], null, null, null, null, null)), (_l()(), i1.ɵeld(52, 0, null, null, 9, "div", [["class", "row"]], null, null, null, null, null)), (_l()(), i1.ɵeld(53, 0, null, null, 2, "div", [["class", "col-md-2 col-sm-12"]], null, null, null, null, null)), (_l()(), i1.ɵeld(54, 0, null, null, 1, "span", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["03"])), (_l()(), i1.ɵeld(56, 0, null, null, 5, "div", [["class", "col-md-10 col-sm-12"]], null, null, null, null, null)), (_l()(), i1.ɵeld(57, 0, null, null, 4, "div", [["class", "fr-text"]], null, null, null, null, null)), (_l()(), i1.ɵeld(58, 0, null, null, 1, "h4", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["every thing you need in one place"])), (_l()(), i1.ɵeld(60, 0, null, null, 1, "p", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, [" stop jumping from one service to another to communicate. store files, track tasks and share documents. manage offers an all-in-one team productitvly solutions "])), (_l()(), i1.ɵeld(62, 0, null, null, 38, "div", [["class", "our-team"], ["id", "customers"]], null, null, null, null, null)), (_l()(), i1.ɵeld(63, 0, null, null, 37, "div", [["class", "container-fluid"]], null, null, null, null, null)), (_l()(), i1.ɵeld(64, 0, null, null, 3, "div", [["class", "row"]], null, null, null, null, null)), (_l()(), i1.ɵeld(65, 0, null, null, 2, "div", [["class", "col-md-12"]], null, null, null, null, null)), (_l()(), i1.ɵeld(66, 0, null, null, 1, "h2", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["what they've said?"])), (_l()(), i1.ɵeld(68, 0, null, null, 28, "div", [["class", "row"], ["id", "slider"]], null, null, null, null, null)), (_l()(), i1.ɵeld(69, 0, null, null, 6, "div", [["class", "col-lg-3 col-md-6 active item-first"]], null, null, null, null, null)), (_l()(), i1.ɵeld(70, 0, null, null, 5, "div", [["class", "team-info"]], null, null, null, null, null)), (_l()(), i1.ɵeld(71, 0, null, null, 0, "img", [["class", "avatar"], ["src", "../../assets/images/avatar-anisha.png"]], null, null, null, null, null)), (_l()(), i1.ɵeld(72, 0, null, null, 1, "h4", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["anisha li"])), (_l()(), i1.ɵeld(74, 0, null, null, 1, "p", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, [" manage has supercharged our team's workflow. the ability to maintain visibilty on larger milestones at all times keeps everyone motivated "])), (_l()(), i1.ɵeld(76, 0, null, null, 6, "div", [["class", "col-lg-3 col-md-6 item-second"]], null, null, null, null, null)), (_l()(), i1.ɵeld(77, 0, null, null, 5, "div", [["class", "team-info"]], null, null, null, null, null)), (_l()(), i1.ɵeld(78, 0, null, null, 0, "img", [["class", "avatar"], ["src", "../../assets/images/avatar-ali.png"]], null, null, null, null, null)), (_l()(), i1.ɵeld(79, 0, null, null, 1, "h4", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["ali bravo"])), (_l()(), i1.ɵeld(81, 0, null, null, 1, "p", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, [" we have able to cancel so many other subscriptions since using manage. there is no more cross-channel confusion and everyone is much more focused "])), (_l()(), i1.ɵeld(83, 0, null, null, 6, "div", [["class", "col-lg-3 col-md-6 item-third"]], null, null, null, null, null)), (_l()(), i1.ɵeld(84, 0, null, null, 5, "div", [["class", "team-info"]], null, null, null, null, null)), (_l()(), i1.ɵeld(85, 0, null, null, 0, "img", [["class", "avatar"], ["src", "../../assets/images/avatar-richard.png"]], null, null, null, null, null)), (_l()(), i1.ɵeld(86, 0, null, null, 1, "h4", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["richard watts"])), (_l()(), i1.ɵeld(88, 0, null, null, 1, "p", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, [" manage allow us to provide structure and process. it keep us organised and focused. i can't stop recommending them to every one i talk to "])), (_l()(), i1.ɵeld(90, 0, null, null, 6, "div", [["class", "col-lg-3 col-md-6 item-four"]], null, null, null, null, null)), (_l()(), i1.ɵeld(91, 0, null, null, 5, "div", [["class", "team-info"]], null, null, null, null, null)), (_l()(), i1.ɵeld(92, 0, null, null, 0, "img", [["class", "avatar"], ["src", "../../assets/images/avatar-shanai.png"]], null, null, null, null, null)), (_l()(), i1.ɵeld(93, 0, null, null, 1, "h4", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["shanai gough"])), (_l()(), i1.ɵeld(95, 0, null, null, 1, "p", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, [" their software allow us to track, manage and collaborate on our projects from anywhere. it keeps the whole team insync without being intrusive "])), (_l()(), i1.ɵeld(97, 0, null, null, 3, "div", [["class", "row"]], null, null, null, null, null)), (_l()(), i1.ɵeld(98, 0, null, null, 2, "div", [["class", "col-md-12"]], null, null, null, null, null)), (_l()(), i1.ɵeld(99, 0, null, null, 1, "button", [["class", "btn btn-primary"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["get started"])), (_l()(), i1.ɵeld(101, 0, null, null, 10, "div", [["class", "start-now"], ["id", "community"]], null, null, null, null, null)), (_l()(), i1.ɵeld(102, 0, null, null, 9, "div", [["class", "container"]], null, null, null, null, null)), (_l()(), i1.ɵeld(103, 0, null, null, 8, "div", [["class", "start-info"]], null, null, null, null, null)), (_l()(), i1.ɵeld(104, 0, null, null, 4, "div", [["class", "start-left"]], null, null, null, null, null)), (_l()(), i1.ɵeld(105, 0, null, null, 3, "h3", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["simplify how your team "])), (_l()(), i1.ɵeld(107, 0, null, null, 0, "br", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, [" works today."])), (_l()(), i1.ɵeld(109, 0, null, null, 2, "div", [["class", "start-right"]], null, null, null, null, null)), (_l()(), i1.ɵeld(110, 0, null, null, 1, "button", [["class", "btn btn-primary"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["get started"])), (_l()(), i1.ɵeld(112, 0, null, null, 57, "div", [["class", "footer"], ["id", "site"]], null, null, null, null, null)), (_l()(), i1.ɵeld(113, 0, null, null, 56, "div", [["class", "container"]], null, null, null, null, null)), (_l()(), i1.ɵeld(114, 0, null, null, 55, "div", [["class", "row"]], null, null, null, null, null)), (_l()(), i1.ɵeld(115, 0, null, null, 19, "div", [["class", "col-md-3 col-sm-12"]], null, null, null, null, null)), (_l()(), i1.ɵeld(116, 0, null, null, 18, "div", [["class", "footer-info social"]], null, null, null, null, null)), (_l()(), i1.ɵeld(117, 0, null, null, 0, "img", [["alt", "logo-footer"], ["src", "../../assets/images/footer-logo.svg"]], null, null, null, null, null)), (_l()(), i1.ɵeld(118, 0, null, null, 16, "div", [["class", "footer-social"]], null, null, null, null, null)), (_l()(), i1.ɵeld(119, 0, null, null, 15, "ul", [["class", "list-unstyled"]], null, null, null, null, null)), (_l()(), i1.ɵeld(120, 0, null, null, 2, "li", [], null, null, null, null, null)), (_l()(), i1.ɵeld(121, 0, null, null, 1, "a", [["href", "javascript:void(0)"]], null, null, null, null, null)), (_l()(), i1.ɵeld(122, 0, null, null, 0, "img", [["alt", "facebook-icon"], ["src", "../../assets/images/icon-facebook.svg"]], null, null, null, null, null)), (_l()(), i1.ɵeld(123, 0, null, null, 2, "li", [], null, null, null, null, null)), (_l()(), i1.ɵeld(124, 0, null, null, 1, "a", [["href", "javascript:void(0)"]], null, null, null, null, null)), (_l()(), i1.ɵeld(125, 0, null, null, 0, "img", [["alt", "youtube-icon"], ["src", "../../assets/images/icon-youtube.svg"]], null, null, null, null, null)), (_l()(), i1.ɵeld(126, 0, null, null, 2, "li", [], null, null, null, null, null)), (_l()(), i1.ɵeld(127, 0, null, null, 1, "a", [["href", "javascript:void(0)"]], null, null, null, null, null)), (_l()(), i1.ɵeld(128, 0, null, null, 0, "img", [["alt", "twitter-icon"], ["src", "../../assets/images/icon-twitter.svg"]], null, null, null, null, null)), (_l()(), i1.ɵeld(129, 0, null, null, 2, "li", [], null, null, null, null, null)), (_l()(), i1.ɵeld(130, 0, null, null, 1, "a", [["href", "javascript:void(0)"]], null, null, null, null, null)), (_l()(), i1.ɵeld(131, 0, null, null, 0, "img", [["alt", "pinterest-icon"], ["src", "../../assets/images/icon-pinterest.svg"]], null, null, null, null, null)), (_l()(), i1.ɵeld(132, 0, null, null, 2, "li", [], null, null, null, null, null)), (_l()(), i1.ɵeld(133, 0, null, null, 1, "a", [["href", "javascript:void(0)"]], null, null, null, null, null)), (_l()(), i1.ɵeld(134, 0, null, null, 0, "img", [["alt", "instagram-icon"], ["src", "../../assets/images/icon-instagram.svg"]], null, null, null, null, null)), (_l()(), i1.ɵeld(135, 0, null, null, 13, "div", [["class", "col-md-3 col-sm-6"]], null, null, null, null, null)), (_l()(), i1.ɵeld(136, 0, null, null, 12, "ul", [["class", "list-unstyled"]], null, null, null, null, null)), (_l()(), i1.ɵeld(137, 0, null, null, 2, "li", [], null, null, null, null, null)), (_l()(), i1.ɵeld(138, 0, null, null, 1, "a", [["href", "javascript:void(0)"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["home"])), (_l()(), i1.ɵeld(140, 0, null, null, 2, "li", [], null, null, null, null, null)), (_l()(), i1.ɵeld(141, 0, null, null, 1, "a", [["href", "javascript:void(0)"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["pricing"])), (_l()(), i1.ɵeld(143, 0, null, null, 2, "li", [], null, null, null, null, null)), (_l()(), i1.ɵeld(144, 0, null, null, 1, "a", [["href", "javascript:void(0)"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["products"])), (_l()(), i1.ɵeld(146, 0, null, null, 2, "li", [], null, null, null, null, null)), (_l()(), i1.ɵeld(147, 0, null, null, 1, "a", [["href", "javascript:void(0)"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["about us"])), (_l()(), i1.ɵeld(149, 0, null, null, 10, "div", [["class", "col-md-3 col-sm-6"]], null, null, null, null, null)), (_l()(), i1.ɵeld(150, 0, null, null, 9, "ul", [["class", "list-unstyled"]], null, null, null, null, null)), (_l()(), i1.ɵeld(151, 0, null, null, 2, "li", [], null, null, null, null, null)), (_l()(), i1.ɵeld(152, 0, null, null, 1, "a", [["href", "javascript:void(0)"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["careers"])), (_l()(), i1.ɵeld(154, 0, null, null, 2, "li", [], null, null, null, null, null)), (_l()(), i1.ɵeld(155, 0, null, null, 1, "a", [["href", "javascript:void(0)"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["community"])), (_l()(), i1.ɵeld(157, 0, null, null, 2, "li", [], null, null, null, null, null)), (_l()(), i1.ɵeld(158, 0, null, null, 1, "a", [["href", "javascript:void(0)"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["privacy policy"])), (_l()(), i1.ɵeld(160, 0, null, null, 9, "div", [["class", "col-md-3 col-sm-12"]], null, null, null, null, null)), (_l()(), i1.ɵeld(161, 0, null, null, 8, "div", [["class", "footer-info forms"]], null, null, null, null, null)), (_l()(), i1.ɵeld(162, 0, null, null, 4, "form", [], null, null, null, null, null)), (_l()(), i1.ɵeld(163, 0, null, null, 3, "div", [["class", "form-group"]], null, null, null, null, null)), (_l()(), i1.ɵeld(164, 0, null, null, 0, "input", [["class", "form-control"], ["placeholder", "updates in your inbox..."], ["type", "text"]], null, null, null, null, null)), (_l()(), i1.ɵeld(165, 0, null, null, 1, "button", [["class", "btn btn-primary"], ["type", "button"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["go"])), (_l()(), i1.ɵeld(167, 0, null, null, 2, "div", [["class", "copyright"]], null, null, null, null, null)), (_l()(), i1.ɵeld(168, 0, null, null, 1, "strong", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["copyright 2020 all rights reserved"])), (_l()(), i1.ɵeld(170, 0, null, null, 1, "div", [["class", "to-top"]], null, null, null, null, null)), (_l()(), i1.ɵeld(171, 0, null, null, 0, "div", [], null, null, null, null, null))], null, null); }
exports.View_HomeComponent_0 = View_HomeComponent_0;
function View_HomeComponent_Host_0(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 1, "app-home", [], null, null, null, View_HomeComponent_0, RenderType_HomeComponent)), i1.ɵdid(1, 114688, null, 0, i2.HomeComponent, [], null, null)], function (_ck, _v) { _ck(_v, 1, 0); }, null); }
exports.View_HomeComponent_Host_0 = View_HomeComponent_Host_0;
var HomeComponentNgFactory = i1.ɵccf("app-home", i2.HomeComponent, View_HomeComponent_Host_0, {}, {}, []);
exports.HomeComponentNgFactory = HomeComponentNgFactory;


/***/ }),

/***/ "./src/app/home/home.component.scss.shim.ngstyle.js":
/*!**********************************************************!*\
  !*** ./src/app/home/home.component.scss.shim.ngstyle.js ***!
  \**********************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = ["\n/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IiIsImZpbGUiOiJzcmMvYXBwL2hvbWUvaG9tZS5jb21wb25lbnQuc2NzcyJ9 */"];
exports.styles = styles;


/***/ }),

/***/ "./src/app/home/home.component.ts":
/*!****************************************!*\
  !*** ./src/app/home/home.component.ts ***!
  \****************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
const core_1 = __webpack_require__(/*! @angular/core */ "@angular/core");
class HomeComponent {
    constructor() { }
    ngOnInit() {
    }
}
exports.HomeComponent = HomeComponent;


/***/ }),

/***/ "./src/app/navbar/navbar.component.ngfactory.js":
/*!******************************************************!*\
  !*** ./src/app/navbar/navbar.component.ngfactory.js ***!
  \******************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
const i0 = __webpack_require__(/*! ./navbar.component.scss.shim.ngstyle */ "./src/app/navbar/navbar.component.scss.shim.ngstyle.js");
const i1 = __webpack_require__(/*! @angular/core */ "@angular/core");
const i2 = __webpack_require__(/*! @angular/router */ "@angular/router");
const i3 = __webpack_require__(/*! @angular/common */ "@angular/common");
const i4 = __webpack_require__(/*! ./navbar.component */ "./src/app/navbar/navbar.component.ts");
var styles_NavbarComponent = [i0.styles];
var RenderType_NavbarComponent = i1.ɵcrt({ encapsulation: 0, styles: styles_NavbarComponent, data: {} });
exports.RenderType_NavbarComponent = RenderType_NavbarComponent;
function View_NavbarComponent_0(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 28, "nav", [["class", "navbar navbar-expand-lg navbar-light"]], null, null, null, null, null)), (_l()(), i1.ɵeld(1, 0, null, null, 27, "div", [["class", "container"]], null, null, null, null, null)), (_l()(), i1.ɵeld(2, 0, null, null, 2, "a", [["class", "navbar-brand"], ["href", "#"], ["routerLink", "/"]], [[1, "target", 0], [8, "href", 4]], [[null, "click"]], function (_v, en, $event) { var ad = true; if (("click" === en)) {
        var pd_0 = (i1.ɵnov(_v, 3).onClick($event.button, $event.ctrlKey, $event.metaKey, $event.shiftKey) !== false);
        ad = (pd_0 && ad);
    } return ad; }, null, null)), i1.ɵdid(3, 671744, null, 0, i2.RouterLinkWithHref, [i2.Router, i2.ActivatedRoute, i3.LocationStrategy], { routerLink: [0, "routerLink"] }, null), (_l()(), i1.ɵeld(4, 0, null, null, 0, "img", [["src", "../../assets/images/logo.svg"]], null, null, null, null, null)), (_l()(), i1.ɵeld(5, 0, null, null, 3, "button", [["aria-controls", "navbarSupportedContent"], ["aria-expanded", "false"], ["aria-label", "Toggle navigation"], ["class", "navbar-toggler"], ["data-toggle", "collapse"], ["type", "button"]], null, null, null, null, null)), (_l()(), i1.ɵeld(6, 0, null, null, 0, "span", [["class", "icon-bars"]], null, null, null, null, null)), (_l()(), i1.ɵeld(7, 0, null, null, 0, "span", [["class", "icon-bars"]], null, null, null, null, null)), (_l()(), i1.ɵeld(8, 0, null, null, 0, "span", [["class", "icon-bars"]], null, null, null, null, null)), (_l()(), i1.ɵeld(9, 0, null, null, 19, "div", [["class", "collapse navbar-collapse"]], null, null, null, null, null)), (_l()(), i1.ɵeld(10, 0, null, null, 15, "ul", [["class", "navbar-nav m-auto"]], null, null, null, null, null)), (_l()(), i1.ɵeld(11, 0, null, null, 2, "li", [["class", "nav-item"]], null, null, null, null, null)), (_l()(), i1.ɵeld(12, 0, null, null, 1, "span", [["class", "nav-link"], ["data-value", "#home"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["home"])), (_l()(), i1.ɵeld(14, 0, null, null, 2, "li", [["class", "nav-item"]], null, null, null, null, null)), (_l()(), i1.ɵeld(15, 0, null, null, 1, "span", [["class", "nav-link"], ["data-value", "#features"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["features"])), (_l()(), i1.ɵeld(17, 0, null, null, 2, "li", [["class", "nav-item"]], null, null, null, null, null)), (_l()(), i1.ɵeld(18, 0, null, null, 1, "span", [["class", "nav-link"], ["data-value", "#customers"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["customers"])), (_l()(), i1.ɵeld(20, 0, null, null, 2, "li", [["class", "nav-item"]], null, null, null, null, null)), (_l()(), i1.ɵeld(21, 0, null, null, 1, "span", [["class", "nav-link"], ["data-value", "#community"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["community"])), (_l()(), i1.ɵeld(23, 0, null, null, 2, "li", [["class", "nav-item"]], null, null, null, null, null)), (_l()(), i1.ɵeld(24, 0, null, null, 1, "span", [["class", "nav-link"], ["data-value", "#site"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["site map"])), (_l()(), i1.ɵeld(26, 0, null, null, 2, "ul", [["class", "navbar-nav ml-auto"]], null, null, null, null, null)), (_l()(), i1.ɵeld(27, 0, null, null, 1, "button", [["class", "btn btn-primary"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["get started"]))], function (_ck, _v) { var currVal_2 = "/"; _ck(_v, 3, 0, currVal_2); }, function (_ck, _v) { var currVal_0 = i1.ɵnov(_v, 3).target; var currVal_1 = i1.ɵnov(_v, 3).href; _ck(_v, 2, 0, currVal_0, currVal_1); }); }
exports.View_NavbarComponent_0 = View_NavbarComponent_0;
function View_NavbarComponent_Host_0(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 1, "app-navbar", [], null, null, null, View_NavbarComponent_0, RenderType_NavbarComponent)), i1.ɵdid(1, 114688, null, 0, i4.NavbarComponent, [], null, null)], function (_ck, _v) { _ck(_v, 1, 0); }, null); }
exports.View_NavbarComponent_Host_0 = View_NavbarComponent_Host_0;
var NavbarComponentNgFactory = i1.ɵccf("app-navbar", i4.NavbarComponent, View_NavbarComponent_Host_0, {}, {}, []);
exports.NavbarComponentNgFactory = NavbarComponentNgFactory;


/***/ }),

/***/ "./src/app/navbar/navbar.component.scss.shim.ngstyle.js":
/*!**************************************************************!*\
  !*** ./src/app/navbar/navbar.component.scss.shim.ngstyle.js ***!
  \**************************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = ["\n/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IiIsImZpbGUiOiJzcmMvYXBwL25hdmJhci9uYXZiYXIuY29tcG9uZW50LnNjc3MifQ== */"];
exports.styles = styles;


/***/ }),

/***/ "./src/app/navbar/navbar.component.ts":
/*!********************************************!*\
  !*** ./src/app/navbar/navbar.component.ts ***!
  \********************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
const core_1 = __webpack_require__(/*! @angular/core */ "@angular/core");
class NavbarComponent {
    constructor() { }
    ngOnInit() {
    }
}
exports.NavbarComponent = NavbarComponent;


/***/ }),

/***/ "./src/environments/environment.ts":
/*!*****************************************!*\
  !*** ./src/environments/environment.ts ***!
  \*****************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

// This file can be replaced during build by using the `fileReplacements` array.
// `ng build --prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.
Object.defineProperty(exports, "__esModule", { value: true });
exports.environment = {
    production: false
};
/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as `zone.run`, `zoneDelegate.invokeTask`.
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */
// import 'zone.js/dist/zone-error';  // Included with Angular CLI.


/***/ }),

/***/ "./src/main.server.ts":
/*!****************************!*\
  !*** ./src/main.server.ts ***!
  \****************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var app_server_module_ngfactory_1 = __webpack_require__(/*! ./app/app.server.module.ngfactory */ "./src/app/app.server.module.ngfactory.js");
exports.AppServerModuleNgFactory = app_server_module_ngfactory_1.AppServerModuleNgFactory;
const core_1 = __webpack_require__(/*! @angular/core */ "@angular/core");
const environment_1 = __webpack_require__(/*! ./environments/environment */ "./src/environments/environment.ts");
if (environment_1.environment.production) {
    core_1.enableProdMode();
}
var app_server_module_1 = __webpack_require__(/*! ./app/app.server.module */ "./src/app/app.server.module.ts");
exports.AppServerModule = app_server_module_1.AppServerModule;
exports.LAZY_MODULE_MAP = {};


/***/ }),

/***/ 0:
/*!**********************************!*\
  !*** multi ./src/main.server.ts ***!
  \**********************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

module.exports = __webpack_require__(/*! E:\ComputersInformatics\Career\1- My_Previous Projects\9- manageLandingPage\src\main.server.ts */"./src/main.server.ts");


/***/ }),

/***/ "@angular/animations":
/*!**************************************!*\
  !*** external "@angular/animations" ***!
  \**************************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/animations");

/***/ }),

/***/ "@angular/animations/browser":
/*!**********************************************!*\
  !*** external "@angular/animations/browser" ***!
  \**********************************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/animations/browser");

/***/ }),

/***/ "@angular/common":
/*!**********************************!*\
  !*** external "@angular/common" ***!
  \**********************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/common");

/***/ }),

/***/ "@angular/common/http":
/*!***************************************!*\
  !*** external "@angular/common/http" ***!
  \***************************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/common/http");

/***/ }),

/***/ "@angular/core":
/*!********************************!*\
  !*** external "@angular/core" ***!
  \********************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/core");

/***/ }),

/***/ "@angular/platform-browser":
/*!********************************************!*\
  !*** external "@angular/platform-browser" ***!
  \********************************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/platform-browser");

/***/ }),

/***/ "@angular/platform-browser/animations":
/*!*******************************************************!*\
  !*** external "@angular/platform-browser/animations" ***!
  \*******************************************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/platform-browser/animations");

/***/ }),

/***/ "@angular/platform-server":
/*!*******************************************!*\
  !*** external "@angular/platform-server" ***!
  \*******************************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/platform-server");

/***/ }),

/***/ "@angular/router":
/*!**********************************!*\
  !*** external "@angular/router" ***!
  \**********************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/router");

/***/ })

/******/ })));
//# sourceMappingURL=main.js.map